select PLANTILLA.HOSPITAL_COD , PLANTILLA.SALA_COD ,  PLANTILLA.EMPLEAT_NO, PLANTILLA.COGNOM
from PLANTILLA
where TORN != "N";

select PLANTILLA.HOSPITAL_COD , PLANTILLA.SALA_COD ,  PLANTILLA.EMPLEAT_NO, PLANTILLA.COGNOM
from PLANTILLA
where TORN IN ("M" , "T");
-- Hace que imprima los que pone "M" o "T"

select PLANTILLA.HOSPITAL_COD , PLANTILLA.SALA_COD ,  PLANTILLA.EMPLEAT_NO, PLANTILLA.COGNOM
from PLANTILLA
where TORN = "M" or TORN = "T";
